-- AlterTable
ALTER TABLE "Paynow" ALTER COLUMN "amount" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "Paypal" ALTER COLUMN "amount" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "Stripe" ALTER COLUMN "amount" SET DATA TYPE DOUBLE PRECISION;
